const messages = [
    "Bestes Skiwetter!!!",
    "Einfach nur geil",
    "Howdi...",
    "Deine Mutter!!",
    "Nice Pisten...",
    "Alter",
    "Geilomat",
    "Scheiß Snowboarder",
    "Blöde Dreckssau",
    "Zu viel los!",
    "Peace!!",
    "Wie geil ist das denn?",
    "Ich könnte Eier legen vor Freude",
    "Gerade ein Ei gelegt",
    "Schnee, Sonne, Sex :D",
    "FICKEN!!!",
    "Gondelfunk rockt",
    "Geile App",
    "das ist sooo lustig",
    "Ich bin der Größte",
    "Skifahrer sind Opfer",
    "Hallo Mama",
    "Yuhuu!!!",
    "Wir haben Spaß",
    "Besser als SEX!!!!",
    "Gondelfunk regelt...",
    "WOW...mit native Canvas?",
    "Geiles Design",
    "Mega flüssige UI",
    "Love it",
    "This is soo great",
    "Amazing"
];

const answers=[
    "Jo!",
    "Hast ja recht!",
    "Yesssss",
    "Fuck you",
    "C'mon",
    "Same, Same",
    "I don't get it",
    "Halts Maul!!",
    "Selber Arschloch",
    "Penner",
    "Deine Mutter",
    "Halt doch dein Maul",
    "Bock auf Sex?"
];

module.exports = {messages,answers};